USE LOCALIDADES;
# 1
-- FAÇA UMA JUNÇÃO DA TABELA CIDADE E ESTADO, MOSTRANDO:
-- NOME DA CIDADE, SIGLA DO ESTADO. APENAS NAS CIDADES QUE TEM ESTADO

# 2
-- FAÇA UMA JUNÇÃO DA TABELA CIDADE E ESTADO, MOSTRANDO:
-- NOME DA CIDADE , SIGLA DO ESTADO. TODAS AS CIDADES, INDEPENDENTE DE TEREM ESTADO

# 3
-- FAÇA UMA JUNÇÃO DA TABELA E ESTADO, MOSTRANDO:
-- NOME DA CIDADE, SIGLA DO ESTADO. MOSTRE TODOS OS ESTADOS, INDEPENDENTE DE TEREM CIDADES

# 4
-- FAÇA UMA JUNÇÃO DA TABELA CIDADE, ESTADO E PREFEITO:
-- CIDADE.NOME,  ESTADO.SIGLA/UF, PREFEITO.NOME, PREFEITO.DATAPOSSE
-- PARA TODAS AS CIDADES QUE TEM PREFEITO

-- 1
SELECT CIDADE.Nome, ESTADO.Sigla
FROM CIDADE
INNER JOIN ESTADO ON CIDADE.Estado_ID = ESTADO.ID;

-- 2
SELECT CIDADE.Nome, ESTADO.Sigla
FROM CIDADE
LEFT JOIN ESTADO ON CIDADE.Estado_ID = ESTADO.ID;

-- 3
SELECT CIDADE.Nome, ESTADO.Sigla
FROM ESTADO
LEFT JOIN CIDADE ON CIDADE.Estado_ID = ESTADO.ID;

-- 4
SELECT CIDADE.Nome, ESTADO.Sigla, PREFEITO.Nome, PREFEITO.DataPosse
FROM CIDADE
LEFT JOIN ESTADO ON CIDADE.Estado_ID = ESTADO.ID
INNER JOIN PREFEITO ON CIDADE.Prefeito_ID = PREFEITO.ID;